-- MySQL Script generated by MySQL Workbench
-- 02/01/16 12:27:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema meet_me
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema meet_me
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meet_me` DEFAULT CHARACTER SET utf8 ;
USE `meet_me` ;

-- -----------------------------------------------------
-- Table `meet_me`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meet_me`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `hash` VARCHAR(255) NULL,
  `recovery_hash` VARCHAR(255) NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `birthday` DATE NULL,
  `city_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meet_me`.`device_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meet_me`.`device_tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_device_tokens_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_device_tokens_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `meet_me`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meet_me`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meet_me`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `place_id` VARCHAR(255) NOT NULL,
  `place_type` VARCHAR(255) NOT NULL,
  `show_name` VARCHAR(255) NULL,
  `comment` VARCHAR(255) NULL,
  `gender` VARCHAR(45) NULL,
  `people` SMALLINT(6) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `lat` DECIMAL(10,6) NOT NULL,
  `lng` DECIMAL(10,6) NOT NULL,
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  `place_info` TEXT NOT NULL,
  PRIMARY KEY (`id`, `lat`),
  INDEX `fk_events_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `meet_me`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meet_me`.`events_to_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meet_me`.`events_to_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `events_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_events_to_users_events1_idx` (`events_id` ASC),
  INDEX `fk_events_to_users_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_events_to_users_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `meet_me`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_to_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `meet_me`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meet_me`.`events_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meet_me`.`events_messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `events_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_messages_events1_idx` (`events_id` ASC),
  INDEX `fk_events_messages_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_events_messages_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `meet_me`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_messages_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `meet_me`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meet_me`.`user_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meet_me`.`user_settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `new_message_push` TINYINT(1) NOT NULL DEFAULT 1,
  `user_left_push` TINYINT(1) NULL DEFAULT 1,
  `user_join_push` TINYINT(1) NULL DEFAULT 1,
  `new_message_email` TINYINT(1) NOT NULL DEFAULT 1,
  `user_left_email` TINYINT(1) NULL DEFAULT 1,
  `user_join_email` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_user_settings_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_user_settings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `meet_me`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
